export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

alias sparkshell='/home/ubuntu/project/spark-1.5.1-bin-hadoop2.6/bin/spark-shell --driver-memory 50G --jars /home/ubuntu/project/warcbase/target/warcbase-0.1.0-SNAPSHOT-fatjar.jar'
alias buildwarcbase='mvn clean package appassembler:assemble -DskipTests'